---
# Source: ring-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: diamond-rings-v1-master
  labels:
    name: diamond-rings
    version: v1
    ring: master
    group: CORE
spec:
  replicas: 1000
  selector:
    matchLabels:
      name: diamond-rings
      version: v1
      ring: master
  template:
    metadata:
      labels:
        name: diamond-rings
        version: v1
        ring: master
    spec:
      containers:
        - name: ring-chart
          image: "helloringsazure.azurecr.io:hello-bedrock-master-5112"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---
# Source: ring-chart/templates/ring.yaml
# Source: hello-ring/templates/ring.yaml
apiVersion: rings.microsoft.com/v1alpha1
kind: Ring
metadata:
  name: diamond-rings-v1-master
  contact: samiya@testing.com
  branchName: bar # Set by pipeline
  buildId: 12345 # Set by pipeline
  buildDate: 2.0190624e+07 # Set by pipeline
  commitId: 43defcs # Set by pipeline
spec:
  # Deploy to environment
  deploy: true
  entryPoints:
    # Source of traffic (eg: 80 or 443)
    - http
    - https
    - internal
  routing:
    service: diamond-rings
    version: v1
    branch: feature/48883-add-search
    group: CORE
    ports:
      - 8080
    initialUsers:
      - bill@contoso.com
      - ted@contoso.com

